### ISSUE TITLE
CglConic does not link to LAPACK in the ThirdParty

### ISSUE THREAD

**Issue by aykutbulut** [aykutbulut/CGL-CONIC#4]
CglConic does not link to the right version of LAPACK that is in the ThirdParty directory. Reported by Saman Eskandarzadeh.

**Comment by aykutbulut** [comment]
It turns out CGL-CONIC links to LAPACK correctly but the required subroutine dsysv is missing in the library. See

https://github.com/coin-or-tools/ThirdParty-Lapack/pull/1

**Comment by tkralphs** [comment]
Fixed.
